const questions=[
  {text:"Qual atividade parece mais interessante?",options:[["Criar telas e experiências","design"],["Resolver problemas com lógica","code"],["Investigar riscos e falhas","security"],["Organizar pessoas e objetivos","business"]]},
  {text:"Em um trabalho em grupo, você prefere...",options:[["Desenhar como a solução será usada","design"],["Construir as partes técnicas","code"],["Testar tudo e procurar problemas","quality"],["Planejar tarefas e conversar com o time","business"]]},
  {text:"Que tipo de desafio chama sua atenção?",options:[["Entender pessoas","design"],["Automatizar uma tarefa","code"],["Descobrir por que algo falhou","quality"],["Encontrar padrões em informações","data"]]},
];
const results={design:["UX/UI Design","Você demonstra interesse por pessoas, comunicação visual e experiências."],code:["Desenvolvimento","Você parece gostar de lógica, construção e solução de problemas."],security:["Cibersegurança","Seu perfil investigativo combina com proteção e análise de riscos."],quality:["Qualidade de Software","Atenção a detalhes e curiosidade sobre falhas são pontos fortes em QA."],business:["Produto e Projetos","Comunicação, organização e visão do todo aparecem no seu perfil."],data:["Dados","Você parece gostar de investigar informações e encontrar padrões."]};
let step=0;const scores={};const title=document.querySelector("[data-quiz-title]");const options=document.querySelector("[data-quiz-options]");const result=document.querySelector("[data-quiz-result]");
function renderQuestion(){const q=questions[step];title.textContent=`${step+1}. ${q.text}`;options.innerHTML=q.options.map(([label,key])=>`<button type="button" data-key="${key}">${label}</button>`).join("");}
options.addEventListener("click",event=>{const button=event.target.closest("[data-key]");if(!button)return;scores[button.dataset.key]=(scores[button.dataset.key]||0)+1;step++;if(step<questions.length)return renderQuestion();const key=Object.keys(scores).sort((a,b)=>scores[b]-scores[a])[0];const [name,copy]=results[key];title.textContent="Seu ponto de partida pode ser:";options.innerHTML="";result.hidden=false;result.innerHTML=`<h3>${name}</h3><p>${copy}</p><a class="btn btn-primary" href="./carreiras.html">Explorar carreiras</a>`;});renderQuestion();
